title: Kat's Blog of Rambles
email: katisntgood@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A site of my random thoughts and such about tech, art, and whatever randomness
  I can think of on top of it.
baseurl: ""
url: "https://katawful.github.io"
github_username:  katawful

author:
  name     : "Kat"
  avatar   : "/assets/images/my-pfp.png"
  bio      : "Weird trans/NB nerd that loves talking about Oblivion, Linux things, and art posting."
  location : "USA, regrettably"
  github: "katawful"
  youtube:
    - channel: "Wood Nerding"
      url: "https://youtube.com/channel/UCSkKqmLx8HkpktRqlapbO2Q"
    - channel: "Gender Ender"
      url: "https://www.youtube.com/channel/UCS7DVUhMMyumSC4BZACMrNw"
  instagram: "woodnerding"
  twitch: "enderofgender"
  nexus:
    account: "katawful"
    url: "https://www.nexusmods.com/users/66104901"

# include folders
include:
  - "_pages"

# Sass stuff
sass:
  sass_dir: _sass

defaults:
        - scope:
                path: ""
                type: "posts"
          values:
                layout: "blog"
                header: /assets/images/generic-header.jpg
                social: true
                permalink: /:categories/:title
                read_time: true
                related: true
                author_profile: true
                sidebar:
                        nav: "sidebar"
