# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-US"
title: Kat's Random Nonsense
name: "Kat"
email: katisntgood@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is just a random collection of my thoughts and experiments.
  Will include some guides and that kind of stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://katawful.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "katawful/github.io"
github_username:  katawful


# Build settings
plugins:
  - jekyll-feed
  - jekyll-include-cache
minimal_mistakes_skin: "gruvbox"

# paginate stuff
paginate: 5
paginate_path: /page:num/

# comment stuff
#emptyArray: []
#
#comments:
#  receiver: https://{{your-receiver-site}}/api/PostComment}}

#collections for categroy
collections:
        category:
                output: true
defaults:
        -
                scope:
                        path: ""
                        type: category
                values:
                        layout: "category"

# include folders
include:
        - "_pages"
        - "_category"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
